apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: <ROLE_NAME>
  namespace: <NAMESPACE>
rules:
- apiGroups:
  - couchbase.database.couchbase.com
  resources:
  - couchbaseclusters
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"
