apiVersion: v1
kind: ConfigMap
metadata:
  name: hazelcast-configuration
data:
  hazelcast.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.10.xsd"
                   xmlns="http://www.hazelcast.com/schema/config"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <properties>
        <property name="hazelcast.discovery.enabled">true</property>
      </properties>
      <map name="hotels">
              <time-to-live-seconds>600</time-to-live-seconds>
              <max-size>200</max-size>
      </map>
      <cache name="hotels">
          <eviction size="200"/>

          <statistics-enabled>true</statistics-enabled>
          <management-enabled>true</management-enabled>
      </cache>
      <network>
        <join>
          <multicast enabled="false"/>
          <tcp-ip enabled="false" />
          <discovery-strategies>
            <discovery-strategy enabled="true" class="com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy">
                <properties>
                    <property name="service-name">hazelcast-service</property>
                                 <property name="service-label-name">hazelcast-service</property>
                                  <property name="service-label-value">true</property>
                                <property name="namespace">default</property>
                </properties>
            </discovery-strategy>
          </discovery-strategies>
        </join>
      </network>
      <management-center enabled="true">http://hazelcast-management-service:8080/hazelcast-mancenter</management-center>
    </hazelcast>